[language.rust]
filetypes = ["rust"]
roots = ["Cargo.toml"]
command = "sh"
args = [
    "-c",
    """
        if path=$(rustup which rust-analyzer 2>/dev/null); then
            "$path"
        else
            rust-analyzer
        fi
    """
]
settings_section = "rust-analyzer"
[language.rust.settings.rust-analyzer]
checkOnSave.command = "clippy"
